name: cyber
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  shared_preferences: ^2.2.2
  dart_jsonwebtoken: ^2.10.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets: 
    - assets/image/
